services:
    Alengo\Bundle\AlengoVoucherBundle\Controller\Admin\VoucherCategoriesController:
        public: 'true'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@alengo_voucher.repository.categories'
            - '@sulu.repository.media'
            - '@alengo_voucher.common.doctrine_list'
            - '@fos_rest.view_handler.default'

    Alengo\Bundle\AlengoVoucherBundle\Controller\Admin\VoucherOrdersController:
        public: 'true'
        arguments:
            - '@alengo_voucher.common.doctrine_list'
            - '@doctrine.orm.default_entity_manager'
            - '@fos_rest.view_handler.default'

    alengo_voucher.controller:
        class: Alengo\Bundle\AlengoVoucherBundle\Controller\VoucherController
        autowire: true
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
            - { name: 'sulu.context', context: 'website' }